/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  lvlvlvlvlvlvlv_                        */
/*      FILE         :  lvlvlvlvlvlvlv_.c                      */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/


#include "iodefine.h"

int main(void) {

    while(1) {
	// TODO: add application code here
    }
return 0;
}
